"""create_documents

Revision ID: 643872a4a76a
Revises: 74290372776e
Create Date: 2026-07-27 01:57:42.521557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '643872a4a76a'
down_revision: Union[str, Sequence[str], None] = '74290372776e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'user_id')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', postgresql.ENUM('UPLOADED', 'PROCESSING', 'INDEXED', 'FAILED', name='documentstatus'), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
