"""add hashed_password to users

Revision ID: 9c4ebfe1b04e
Revises: 31f096ed6ee2
Create Date: 2026-08-05 18:41:13.101018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4ebfe1b04e'
down_revision: Union[str, Sequence[str], None] = '31f096ed6ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Step 1: Add column as nullable
    op.add_column(
        "users",
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=True,
        ),
    )

    # Step 2: Populate existing rows
    op.execute(
        """
        UPDATE users
        SET hashed_password = ''
        WHERE hashed_password IS NULL
        """
    )

    # Step 3: Make column NOT NULL
    op.alter_column(
        "users",
        "hashed_password",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
